Repository 4fra/plutomierz, pull requests merged in 2024-12, with the labels that each got.

#13 Update API, improve web ui, add chart and improvements in Android app.
  android/app/src/main/java/com/fra/plutomierz/receiver/PlutaReminderReceiver.kt
  android/app/src/main/java/com/fra/plutomierz/ui/SettingsActivity.kt
  api/src/db/db.ts
  api/src/db/initDb.ts
  api/src/db/plutaLogDb.ts
  api/src/plutaValue/getPlutaValue.ts
  api/src/plutaValue/utils/getCurrentEventMultiplier.ts
  api/src/plutaValue/utils/getTimeAtPluta.ts
  api/src/plutaValue/utils/getWeatherData.ts
  api/src/utils/getPlutaValue.ts
  api/src/websocket/utils/discordWebhook.ts
  api/src/websocket/utils/rateLimiter.ts
  api/src/websocket/utils/updatePlutaValue.ts
  api/src/websocket/utils/validation.ts
  api/src/websocket/utils/websocketServer.ts
  api/src/websocket/websocket.ts
  api/tests/websocket/utils/validate.test.ts
  package-lock.json
  package.json
  web/src/components/background/Background.css
  web/src/components/clock/Clock.css
  web/src/components/clock/Clock.jsx
  web/src/components/dayComment/DayComment.css
  web/src/components/dayComment/DayComment.jsx
  web/src/components/plutoGraph/PlutoGraph.css
  web/src/components/plutoGraph/PlutoGraph.jsx
  web/src/components/plutomierz/Plutomierz.css
  web/src/components/plutomierz/Plutomierz.jsx
  web/src/components/splash/Splash.css
  web/src/components/splash/Splash.jsx
  web/src/components/title/Title.css
  web/src/components/title/Title.jsx
  web/src/graph/Graph.css
  web/src/graph/Graph.jsx
  web/src/home/Home.css
  web/src/home/Home.jsx
  web/src/main.jsx
Labels: Adam Pluta

#14 Moved required dependencies to web directory.
  package.json
  web/package.json
Labels: Adam Pluta

#17 ✨ API: Add timestamps to chat messages
  api/src/db/handleMessageDb.ts
  api/src/types/ChatMessage.ts
  api/src/websocket/websocket.ts
Labels: Adam Pluta

#25 API: handle message type sent by client
  api/src/websocket/websocket.ts
Labels: Adam Pluta

#19 :sparkles: API: Broadcast onlajt users count
  api/src/websocket/utils/activeUsersCount.ts
  api/src/websocket/websocket.ts
Labels: Adam Pluta

#35 API: Prevent crashes in Pluta log endpoint
  api/src/db/plutaLogDb.ts
  api/src/websocket/websocket.ts
Labels: bug, Adam Pluta

#32 WEB - Use local API on dev
  web/src/components/websocketContext.jsx
Labels: Adam Pluta

#29 Android: display timestamps
  android/app/src/main/java/com/fra/plutomierz/ui/ChatHistory.kt
  android/app/src/main/java/com/fra/plutomierz/ui/MainActivity.kt
Labels: Adam Pluta

#39 Feature/api/additional pluta value variables
  api/src/plutaValue/calcFactorFunctions/break.ts
  api/src/plutaValue/calcFactorFunctions/day.ts
  api/src/plutaValue/calcFactorFunctions/month.ts
  api/src/plutaValue/calcFactorFunctions/rain.ts
  api/src/plutaValue/calcFactorFunctions/randomPlutaTime.ts
  api/src/plutaValue/calcFactorFunctions/sinusoidalBonusBetweenHours.ts
  api/src/plutaValue/calcFactorFunctions/snow.ts
  api/src/plutaValue/calcFactorFunctions/sunlight.ts
  api/src/plutaValue/calcFactorFunctions/temperature.ts
  api/src/plutaValue/calcFactorFunctions/theMoreTheWorse.ts
  api/src/plutaValue/calcFactorFunctions/uv.ts
  api/src/plutaValue/calcFactorFunctions/weekendNight.ts
  api/src/plutaValue/calcFactorFunctions/wind.ts
  api/src/plutaValue/calcFactorFunctions/windDirection.ts
  api/src/plutaValue/getPlutaValue.ts
  api/src/websocket/utils/discordWebhook.ts
  api/src/websocket/utils/updatePlutaValue.ts
  api/src/websocket/websocket.ts
Labels: Adam Pluta

#44 Web: New website UI
  web/public/assets/menu/mainIcon.webp
  web/src/components/background/Background.css
  web/src/components/clock/Clock.css
  web/src/components/clock/Clock.jsx
  web/src/components/dayComment/DayComment.css
  web/src/components/dayComment/DayComment.jsx
  web/src/components/livechat/Livechat.css
  web/src/components/livechat/Livechat.jsx
  web/src/components/plutaTimer/PlutaTimer.css
  web/src/components/plutaTimer/PlutaTimer.jsx
  web/src/components/plutomierz/Plutomierz.css
  web/src/components/plutomierz/Plutomierz.jsx
  web/src/components/splash/Splash.css
  web/src/components/splash/Splash.jsx
  web/src/home/Home.css
  web/src/home/Home.jsx
  web/src/index.css
  web/src/pages/main/Main.css
  web/src/pages/main/Main.jsx
  web/src/routes/routes.jsx
  web/src/utils/cookies.ts
Labels: enhancement

#46 API: Fix invalid trimming logic in message validation
  api/src/websocket/utils/validation.ts
Labels: bug, Adam Pluta

#47 Feature/web/graph data range selection
  api/src/websocket/websocket.ts
  web/src/components/livechat/Livechat.jsx
  web/src/components/plutoGraph/PlutoGraph.css
  web/src/components/plutomierz/Plutomierz.jsx
  web/src/graph/Graph.jsx
  web/src/graph/components/dateSelection/DateSelection.css
  web/src/graph/components/dateSelection/DateSelection.jsx
  web/src/graph/components/plutoGraph/PlutoGraph.css
  web/src/graph/components/plutoGraph/PlutoGraph.jsx
  web/src/graph/utils/usePlutaLog.jsx
  web/src/main.jsx
  web/src/utils/websocketContext.jsx
Labels: enhancement, Adam Pluta

#45 Android: display plutograph
  android/app/build.gradle.kts
  android/app/src/main/assets/motivationalPluta.json
  android/app/src/main/java/com/fra/plutomierz/ui/MainActivity.kt
  android/app/src/main/java/com/fra/plutomierz/ui/components/ChatHistory.kt
  android/app/src/main/java/com/fra/plutomierz/ui/components/ChatInput.kt
  android/app/src/main/java/com/fra/plutomierz/ui/components/MotivationalText.kt
  android/app/src/main/java/com/fra/plutomierz/ui/components/PlutaChart.kt
  android/app/src/main/java/com/fra/plutomierz/ui/components/Plutometer.kt
  android/app/src/main/java/com/fra/plutomierz/ui/components/TopBar.kt
  android/gradle/libs.versions.toml
  android/settings.gradle.kts
Labels: enhancement, Adam Pluta

#54 Android: Display active user count
  android/app/src/main/java/com/fra/plutomierz/ui/MainActivity.kt
Labels: enhancement, Adam Pluta

#55 Docs: README and API documetation.
  API.md
  LICENSE
  README.md
Labels: documentation

#57 Android: Allow user to change username only one time
  android/app/src/main/java/com/fra/plutomierz/data/PreferencesHelper.kt
  android/app/src/main/java/com/fra/plutomierz/ui/SettingsActivity.kt
  android/app/src/main/java/com/fra/plutomierz/ui/components/ChatInput.kt
Labels: enhancement

#60 Web: Menu for switching between Plutomierz and Plutograf
  web/src/graph/Graph.css
  web/src/graph/components/plutoGraph/PlutoGraph.css
  web/src/home/Home.css
  web/src/home/Home.jsx
  web/src/main.jsx
  web/src/pages/main/Main.css
  web/src/pages/main/Main.jsx
  web/src/pages/sponsors/Sponsors.css
  web/src/pages/sponsors/Sponsors.jsx
  web/src/routes/routes.jsx
Labels: enhancement

#62 Api: Bugfix to weekend midnight pluta, pluta value adjustments
  api/src/plutaValue/calcFactorFunctions/break.ts
  api/src/plutaValue/calcFactorFunctions/weekendNight.ts
  api/src/plutaValue/getPlutaValue.ts
Labels: bug

#64 Api/Web: currentEventDescription sending and display on website
  api/src/db/handleEventsDb.ts
  api/src/plutaValue/getPlutaValue.ts
  api/src/websocket/websocket.ts
  web/src/components/splash/Splash.jsx
Labels: enhancement

#59 API: Event system
  api/src/db/handleEventsDb.ts
  api/src/db/handleVotesDb.ts
  api/src/db/initDb.ts
  api/src/plutaValue/getPlutaValue.ts
  api/src/plutaValue/utils/accountEvents.ts
  api/src/plutaValue/utils/accountVotes.ts
  api/src/types/Event.ts
  api/src/types/Vote.ts
  api/src/websocket/utils/handleChatMessage.ts
  api/src/websocket/utils/handleGetPlutaLog.ts
  api/src/websocket/websocket.ts
  web/src/components/splash/Splash.jsx
Labels: enhancement

#63 Web: Move active users display to chat header
  web/src/components/activeUsers/ActiveUsers.css
  web/src/components/livechat/Livechat.css
  web/src/components/livechat/Livechat.jsx
  web/src/pages/main/Main.css
  web/src/pages/main/Main.jsx
Labels: bug, enhancement

#66 Release: Merry Pluta Update
  API.md
  LICENSE
  README.md
  android/app/build.gradle.kts
  android/app/src/main/assets/motivationalPluta.json
  android/app/src/main/java/com/fra/plutomierz/data/PreferencesHelper.kt
  android/app/src/main/java/com/fra/plutomierz/ui/MainActivity.kt
  android/app/src/main/java/com/fra/plutomierz/ui/SettingsActivity.kt
  android/app/src/main/java/com/fra/plutomierz/ui/components/ChatHistory.kt
  android/app/src/main/java/com/fra/plutomierz/ui/components/ChatInput.kt
  android/app/src/main/java/com/fra/plutomierz/ui/components/MotivationalText.kt
  android/app/src/main/java/com/fra/plutomierz/ui/components/PlutaChart.kt
  android/app/src/main/java/com/fra/plutomierz/ui/components/Plutometer.kt
  android/app/src/main/java/com/fra/plutomierz/ui/components/TopBar.kt
  android/gradle/libs.versions.toml
  android/settings.gradle.kts
  api/src/db/handleEventsDb.ts
  api/src/db/handleVotesDb.ts
  api/src/db/initDb.ts
  api/src/plutaValue/calcFactorFunctions/break.ts
  api/src/plutaValue/calcFactorFunctions/weekendNight.ts
  api/src/plutaValue/getPlutaValue.ts
  api/src/plutaValue/utils/accountEvents.ts
  api/src/plutaValue/utils/accountVotes.ts
  api/src/types/Event.ts
  api/src/types/Vote.ts
  api/src/websocket/utils/handleChatMessage.ts
  api/src/websocket/utils/handleGetPlutaLog.ts
  api/src/websocket/websocket.ts
  web/public/assets/activeUsers/account.png
  web/src/components/activeUsers/ActiveUsers.css
  web/src/components/activeUsers/ActiveUsers.jsx
  web/src/components/livechat/Livechat.css
  web/src/components/livechat/Livechat.jsx
  web/src/components/plutaTimer/PlutaTimer.jsx
  web/src/components/splash/Splash.jsx
  web/src/graph/Graph.css
  web/src/graph/components/plutoGraph/PlutoGraph.css
  web/src/home/Home.css
  web/src/home/Home.jsx
  web/src/main.jsx
  web/src/pages/main/Main.css
  web/src/pages/main/Main.jsx
  web/src/pages/sponsors/Sponsors.css
  web/src/pages/sponsors/Sponsors.jsx
  web/src/routes/routes.jsx
  web/src/utils/websocketWorker.jsx
Labels: Adam Pluta
